
[[artifacts]]
git-tree-sha1 = "2c98d98e06b42bbdac3a8b4386d0de8cd476327b"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.4.2/artifacts-linux-x86_64.tar.gz"
    sha256 = "0b4b181bf96447d7019f7d9b5e212648084cfc6d851eaf8643edfe75c2b06a21"

[[artifacts]]
git-tree-sha1 = "c95d1116bbc5919111151b3b1c983c691b243fb9"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Magic.jl/releases/download/v0.4.2/artifacts-win64.tar.gz"
    sha256 = "774c502030a3b633aa35e015ee6f5b82ba97be0caf9d7adf83d8f14ef690f78e"

