[artifacts]
git-tree-sha1 = "4f6365130260f932784b99428223cb4c840a52f1"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.1.0-a/artifacts-linux-x86_64.tar.gz"
    sha256 = "ef50e2007f92cabf307679dbb12dc09d005f15fbe592bc2555cbca17daf74608"
    os = "linux"
    arch = "x86_64"
