[[artifacts]]
git-tree-sha1 = "fbd05b712bbb9a4cab2dd1481ca3b844788af431"
os = "linux"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.2.4/artifacts-linux-x86_64.tar.gz"
    sha256 = "6983db7d988220adb9011248014df26589bb26e2fba1b8fa9ac6c6f5724d13cd"

[[artifacts]]
git-tree-sha1 = "aba345a1a0f56593c981d8ad7a9b593536d299d8"
os = "windows"
arch = "x86_64"

    [[artifacts.download]]
    url = "https://github.com/nidoro/Lit.jl/releases/download/v0.2.4/artifacts-win64.tar.gz"
    sha256 = "3299ff8a064760424015408d448b8ff293113c23c2751460bab8d9fce66ad642"
