name = "Magic"
uuid = "938144cb-3a24-4977-a248-a12dea9dd101"
authors = ["Davi Doro <ni.doro@gmail.com>"]
version = "0.4.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[compat]
Random = "1.10"
Libdl = "1.10"
SHA = "0.7"
JSON = "0.21, 1.0"
Tables = "1.12"
julia = "1.10"
DataFrames = "1.8"
Parameters = "0.12"
Logging = "1.10"
Sockets = "1.10"
ArgParse = "1.2"
Artifacts = "1.10"
TOML = "1.0"
