[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Lit = "938144cb-3a24-4977-a248-a12dea9dd101"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
VegaDatasets = "0ae4a718-28b7-58ec-9efb-cded64d6d5b4"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[sources.Lit]
path = ".."
